### ISSUE TITLE
AWX 13 broken due upstream issues

### ISSUE THREAD

**Issue by ikke-t** [ikke-t/awx_pod#18]
Permission issues: 

- https://github.com/ansible/awx/issues/7545
- https://github.com/ansible/awx/issues/7544

So let's label awx_pod with 13.0 once those are fixed. This module is broken due those ATM at master branch. If you want to use a working module, select earlier version.

**Comment by Klaas-** [comment]
memcached was removed from awx in 12, I'd guess we need to change this role to reflect the upstream changes in kubernetes role; CCing @cfelder  https://github.com/ansible/awx/pull/7240

**Comment by Klaas-** [comment]
https://github.com/ikke-t/awx_pod/blob/master/templates/settings.py.j2
https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/configmap.yml.j2#L128-L202

and

https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/deployment.yml.j2
https://github.com/ikke-t/awx_pod/blob/master/templates/awx.yml.j2

don't have my test setup ready at the moment so I won't get around to that soon :D

**Comment by ikke-t** [comment]
I suppose the order of getting this back to work would be to submit PRs to awx about those two starter script execute bits. Then waiting to get the upstream containers being rebuilt to work with PR changes. Once having those in place, there is place to make and test the  above changes to drop memcached and update settings.

Creating the PR is small job, I wonder if @cfelder already has the changes in his repo?

I have a bit quieter time at work than usual, I could also do some of this one day.

**Comment by cfelder** [comment]
I am already on it (removing memcache).

I'll also post an example playbook here to run with a derived container image which has already fixed executable bits.

If I'll find the correct spot in the awx repo I can make a PR as well for fixing those Dockerfiles.

**Comment by cfelder** [comment]
The following example uses a derived container with fixed acls and removed preloading data into awx as well.

```
- name: run AWX on host
  hosts: all
  become: yes
  vars:
    awx_pod_name: awx
  tasks:
    - include_role:
        name: awx_pod
      vars:
        awx_admin_user: admin
        awx_admin_password: foobar
        awx_podman_dir: /tmp
        awx_host_port: 8052
        awx_pod_label: awx
        awx_awx_image: quay.io/cfelder/awx:nopreload-{{ awx_awx_version }}
```

Dockerfile
```
FROM docker.io/ansible/awx:13.0.0
LABEL maintainer="Christian Felder"

USER root

RUN dnf update -y && \
  dnf clean all -y
RUN sed -i '/.*awx-manage.*create_preload_data.*/d' \
  /usr/bin/launch_awx_task.sh \
  && \
 chmod 755 /usr/bin/launch_awx*.sh

USER 1000
```

needs: #19
